AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-sam-app

  Sample SAM Template for sample-sam-app

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  S3BucketName:
    Type: String
    Default: "sample-app-bucket"
  MessageTableName:
    Type: String
    Default: "Message"
  MemberTableName:
    Type: String
    Default: "Member"

Resources:
  # S3: test-data bucket
  SampleAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      BucketName: !Ref S3BucketName

  # DynamoDB: Message table
  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: seq
          AttributeType: N
      KeySchema:
        - AttributeName: seq
          KeyType: HASH
      TableName: !Ref MessageTableName
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # DynamoDB: Member table
  MemberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: seq
          AttributeType: N
      KeySchema:
        - AttributeName: seq
          KeyType: HASH
      TableName: !Ref MemberTableName
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # Lambda: HelloWorldFunction
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: hello_world.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::000000000000:role/lambda-role
      Architectures:
        - x86_64

  # Lambda: SimpleResponseFunction
  SimpleResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: simple_response.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::000000000000:role/lambda-role
      Architectures:
        - x86_64

  # Lambda: AddMessageFunction
  AddMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: add_message.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::000000000000:role/lambda-role
      Architectures:
        - x86_64

  # Lambda: UpdateMemberFileFunction
  UpdateMemberFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: update_member_file.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::000000000000:role/lambda-role
      Architectures:
        - x86_64
      Events:
        MemberTableUpdate:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MemberTable.StreamArn
            StartingPosition: LATEST
            Enabled: true
