# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sample-sam-app"
parameter_overrides = [
    "S3BucketName=sample-app-bucket",
    "MessageTableName=Message",
    "MemberTableName=Member",
    "LambdaExecutionRoleArn=ARBITRARY-EXECUTION-ROLE-ARN",
    "BookTableStreamArn=ARBITRARY-DYNAMODB-STREAM-ARN"
]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sample-sam-app"
region = "ap-northeast-3"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[local]
[local.global.parameters]
stack_name = "sample-sam-app-local"
parameter_overrides = [
    "S3BucketName=sample-app-bucket",
    "MessageTableName=Message",
    "MemberTableName=Member",
    "LambdaExecutionRoleArn=arn:aws:iam::000000000000:role/lambda-role",
    "BookTableStreamArn=arn:aws:dynamodb:ap-northeast-3:000000000000:table/Book/stream/2024-08-28T07:47:22.051"
]
